import Image from "next/image";
import type { SVGProps } from "react";

// Monogram R: three tape strips with round caps (grid 146x200, stroke 24). See DESIGN.md.
export function LogoSymbol(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 146 200" fill="none" aria-hidden="true" {...props}>
      <g stroke="currentColor" strokeWidth={24} strokeLinecap="round" strokeLinejoin="round">
        <path d="M20 22V178" />
        <path d="M52 22H74C106 22 126 43 126 70C126 97 106 118 74 118H52" />
        <path d="M95 148L125 178" />
      </g>
    </svg>
  );
}

// Lockups come from public/brand (generated by scripts/build-brand.mjs), so the site and every
// other use of the logo share the exact same drawing.
const lockups = {
  horizontal: { file: "logo-horizontal", width: 259, height: 62 },
  vertical: { file: "logo-vertical", width: 201, height: 273 },
};

type LogoProps = {
  className?: string;
  orientation?: keyof typeof lockups;
  tone?: "wine" | "cream";
  priority?: boolean;
};

export function Logo({ className, orientation = "horizontal", tone = "wine", priority }: LogoProps) {
  const { file, width, height } = lockups[orientation];
  return (
    <Image
      src={`/brand/${file}${tone === "cream" ? "-negativo" : ""}.svg`}
      width={width}
      height={height}
      alt="Rufino Clinical"
      unoptimized
      priority={priority}
      className={className}
    />
  );
}
