-- DEVELOPMENT CATALOG: placeholder products so the storefront can be built before the real catalog.
-- Every SKU starts with DEV-. Remove before launch with supabase/seed/remove_dev_catalog.sql.
-- Copy, prices and dimensions are illustrative and must be replaced by the client's real data.

insert into public.categories (slug, name, description, position) values
  ('bandagem-elastica', 'Bandagem elástica', 'Tapes para drenagem, suporte e recuperação.', 1),
  ('compressao', 'Compressão', 'Braçadeiras e meias de compressão graduada.', 2),
  ('pos-operatorio', 'Pós-operatório', 'Espumas e placas para o pós-cirúrgico.', 3),
  ('enfaixamento', 'Enfaixamento', 'Ataduras e kits para enfaixamento compressivo.', 4)
on conflict (slug) do nothing;

with c as (select id, slug from public.categories)
insert into public.products (slug, name, category_id, short_description, description, usage_instructions, indications, is_active, is_featured, position) values
  ('kinesio-tape-5cm', 'Kinesio Tape 5 cm x 5 m', (select id from c where slug = 'bandagem-elastica'),
   'Bandagem elástica de algodão com adesivo hipoalergênico.',
   'Fita elástica de algodão com adesivo acrílico ativado pelo calor do corpo. Elasticidade próxima à da pele, respirável e resistente à água.',
   'Limpe e seque a pele. Arredonde as pontas, remova o papel protetor sem tocar o adesivo e aplique conforme a técnica indicada pelo fisioterapeuta. Esfregue levemente para ativar o adesivo.',
   'Drenagem linfática, edemas, equimoses e suporte muscular, sempre com orientação profissional.',
   true, true, 1),
  ('kinesio-tape-leque', 'Kinesio Tape pré-cortada em leque', (select id from c where slug = 'bandagem-elastica'),
   'Tiras já cortadas para aplicação linfática.',
   'Bandagem elástica pré-cortada em formato de leque, pronta para técnicas de drenagem linfática. Economiza tempo no consultório e padroniza a aplicação.',
   'Aplique a base próxima ao linfonodo de referência e distribua as tiras sem tensão sobre a área de edema.',
   'Edemas pós-operatórios e linfedema, sob orientação profissional.',
   true, true, 2),
  ('bandagem-elastica-7cm', 'Bandagem elástica 7,5 cm x 5 m', (select id from c where slug = 'bandagem-elastica'),
   'Largura extra para áreas amplas como abdômen e coxas.',
   'Versão mais larga da bandagem elástica, indicada para regiões extensas. Mesmo adesivo hipoalergênico e tecido respirável.',
   'Corte no tamanho desejado, arredonde as pontas e aplique sobre a pele limpa e seca.',
   'Pós-operatório de abdominoplastia e lipoaspiração, sob orientação profissional.',
   true, false, 3),
  ('tesoura-antiaderente', 'Tesoura antiaderente para bandagem', (select id from c where slug = 'bandagem-elastica'),
   'Lâminas com revestimento que não gruda no adesivo.',
   'Tesoura com lâminas revestidas que evitam o acúmulo de cola ao cortar bandagens elásticas. Corte limpo e preciso.',
   'Limpe as lâminas com pano seco após o uso.',
   'Uso profissional e doméstico no preparo de bandagens.',
   true, false, 4),
  ('bracadeira-compressao-20-30', 'Braçadeira de compressão 20-30 mmHg', (select id from c where slug = 'compressao'),
   'Compressão graduada para membro superior.',
   'Braçadeira em malha circular com compressão graduada de 20 a 30 mmHg. Acabamento em silicone para melhor fixação.',
   'Vista pela manhã, com o braço sem edema. Retire para dormir, salvo orientação contrária.',
   'Linfedema de membro superior e pós-operatório de mama, com prescrição profissional.',
   true, true, 5),
  ('meia-compressao-3-4', 'Meia de compressão 3/4 20-30 mmHg', (select id from c where slug = 'compressao'),
   'Meia até o joelho com ponteira aberta.',
   'Meia de compressão graduada até o joelho, com ponteira aberta e fio respirável para uso diário.',
   'Calce pela manhã, antes de o edema se formar. Use um calçador se necessário.',
   'Insuficiência venosa leve a moderada e edema de membros inferiores, com prescrição profissional.',
   true, false, 6),
  ('espuma-pos-operatoria', 'Espuma de compressão pós-operatória', (select id from c where slug = 'pos-operatorio'),
   'Distribui a pressão da cinta e evita marcas na pele.',
   'Placa de espuma macia para uso sob a cinta modeladora. Uniformiza a compressão e reduz o risco de fibrose e marcas.',
   'Posicione sobre a área tratada, sob a cinta. Troque ou higienize conforme orientação.',
   'Pós-operatório de lipoaspiração e abdominoplastia.',
   true, true, 7),
  ('placa-abdominal', 'Placa abdominal pós-lipo', (select id from c where slug = 'pos-operatorio'),
   'Placa rígida para uniformizar a compressão no abdômen.',
   'Placa semirrígida com bordas arredondadas, usada sobre a espuma e sob a cinta para manter o abdômen uniforme.',
   'Use sobre a espuma, sob a cinta, conforme orientação do cirurgião ou fisioterapeuta.',
   'Pós-operatório de lipoaspiração abdominal.',
   true, false, 8),
  ('atadura-curta-elasticidade', 'Atadura de curta elasticidade 10 cm', (select id from c where slug = 'enfaixamento'),
   'Para enfaixamento compressivo multicamadas.',
   'Atadura de algodão de curta elasticidade, alta pressão de trabalho e baixa pressão de repouso. Reutilizável e lavável.',
   'Aplique em espiral ou em oito, do distal para o proximal, conforme a técnica do enfaixamento.',
   'Terapia descongestiva complexa para linfedema.',
   true, false, 9),
  ('kit-enfaixamento-braco', 'Kit enfaixamento linfático para braço', (select id from c where slug = 'enfaixamento'),
   'Tudo o que é preciso para o enfaixamento do membro superior.',
   'Kit com malha tubular, algodão ortopédico e ataduras de curta elasticidade em larguras variadas.',
   'Siga a sequência de camadas orientada pelo fisioterapeuta.',
   'Fase intensiva da terapia descongestiva complexa.',
   true, true, 10)
on conflict (slug) do nothing;

with p as (select id, slug from public.products)
insert into public.product_variants (product_id, sku, name, options, price_cents, compare_at_price_cents, stock_quantity, weight_grams, length_cm, width_cm, height_cm, position) values
  ((select id from p where slug = 'kinesio-tape-5cm'), 'DEV-KT5-BEGE', 'Bege', '{"cor":"Bege"}', 4990, null, 40, 120, 8, 8, 6, 1),
  ((select id from p where slug = 'kinesio-tape-5cm'), 'DEV-KT5-PRETO', 'Preto', '{"cor":"Preto"}', 4990, null, 25, 120, 8, 8, 6, 2),
  ((select id from p where slug = 'kinesio-tape-5cm'), 'DEV-KT5-ROSA', 'Rosa', '{"cor":"Rosa"}', 4990, null, 3, 120, 8, 8, 6, 3),
  ((select id from p where slug = 'kinesio-tape-leque'), 'DEV-KTL-BEGE', 'Bege, 10 unidades', '{"cor":"Bege"}', 3990, 4590, 30, 60, 20, 12, 2, 1),
  ((select id from p where slug = 'bandagem-elastica-7cm'), 'DEV-BE7-BEGE', 'Bege', '{"cor":"Bege"}', 6990, null, 18, 180, 10, 10, 8, 1),
  ((select id from p where slug = 'bandagem-elastica-7cm'), 'DEV-BE7-PRETO', 'Preto', '{"cor":"Preto"}', 6990, null, 0, 180, 10, 10, 8, 2),
  ((select id from p where slug = 'tesoura-antiaderente'), 'DEV-TES-01', 'Único', '{}', 4490, null, 12, 90, 20, 8, 2, 1),
  ((select id from p where slug = 'bracadeira-compressao-20-30'), 'DEV-BRC-P', 'P', '{"tamanho":"P"}', 28990, null, 5, 150, 25, 12, 3, 1),
  ((select id from p where slug = 'bracadeira-compressao-20-30'), 'DEV-BRC-M', 'M', '{"tamanho":"M"}', 28990, null, 8, 160, 25, 12, 3, 2),
  ((select id from p where slug = 'bracadeira-compressao-20-30'), 'DEV-BRC-G', 'G', '{"tamanho":"G"}', 28990, null, 4, 170, 25, 12, 3, 3),
  ((select id from p where slug = 'meia-compressao-3-4'), 'DEV-MC34-P', 'P', '{"tamanho":"P"}', 19990, 22990, 10, 120, 22, 12, 3, 1),
  ((select id from p where slug = 'meia-compressao-3-4'), 'DEV-MC34-M', 'M', '{"tamanho":"M"}', 19990, 22990, 14, 130, 22, 12, 3, 2),
  ((select id from p where slug = 'meia-compressao-3-4'), 'DEV-MC34-G', 'G', '{"tamanho":"G"}', 19990, 22990, 6, 140, 22, 12, 3, 3),
  ((select id from p where slug = 'espuma-pos-operatoria'), 'DEV-ESP-P', 'P', '{"tamanho":"P"}', 8990, null, 20, 150, 35, 25, 2, 1),
  ((select id from p where slug = 'espuma-pos-operatoria'), 'DEV-ESP-M', 'M', '{"tamanho":"M"}', 9490, null, 20, 180, 40, 30, 2, 2),
  ((select id from p where slug = 'espuma-pos-operatoria'), 'DEV-ESP-G', 'G', '{"tamanho":"G"}', 9990, null, 15, 210, 45, 35, 2, 3),
  ((select id from p where slug = 'placa-abdominal'), 'DEV-PLA-01', 'Tamanho único', '{}', 7990, null, 22, 250, 35, 30, 2, 1),
  ((select id from p where slug = 'atadura-curta-elasticidade'), 'DEV-ACE-10', '10 cm x 5 m', '{"largura":"10 cm"}', 5990, null, 30, 110, 12, 10, 10, 1),
  ((select id from p where slug = 'kit-enfaixamento-braco'), 'DEV-KEB-01', 'Kit completo', '{}', 24990, 27990, 7, 900, 30, 25, 12, 1)
on conflict (sku) do nothing;
